#ifndef SRC_GRAPHICS_TEXT_FREETYPE_FREE_TYPE_FONT_LOADER_H
#define SRC_GRAPHICS_TEXT_FREETYPE_FREE_TYPE_FONT_LOADER_H

namespace karin
{
class FreeTypeFontLoader
{
};
} // karin

#endif //SRC_GRAPHICS_TEXT_FREETYPE_FREE_TYPE_FONT_LOADER_H