#ifndef SRC_GRAPHICS_TEXT_UNIX_FREETYPE_FONTCONFIG_FONT_LOADER_H
#define SRC_GRAPHICS_TEXT_UNIX_FREETYPE_FONTCONFIG_FONT_LOADER_H

namespace karin
{
class FreeTypeFontConfigFontLoader : IPlatformFontLoader
{
};
} // karin

#endif //SRC_GRAPHICS_TEXT_UNIX_FREETYPE_FONTCONFIG_FONT_LOADER_H