#ifndef SRC_GRAPHICS_TEXT_WINDOWS_DWRITE_FONT_RENDERER_H
#define SRC_GRAPHICS_TEXT_WINDOWS_DWRITE_FONT_RENDERER_H

namespace karin
{
class DwriteFontRenderer
{
};
} // karin

#endif //SRC_GRAPHICS_TEXT_WINDOWS_DWRITE_FONT_RENDERER_H