#ifndef SRC_GRAPHICS_TEXT_WINDOWS_FREETYPE_DWRITE_FONT_LOADER_H
#define SRC_GRAPHICS_TEXT_WINDOWS_FREETYPE_DWRITE_FONT_LOADER_H

namespace karin
{
class FreeTypeDWriteFontLoader
{
};
} // karin

#endif //SRC_GRAPHICS_TEXT_WINDOWS_FREETYPE_DWRITE_FONT_LOADER_H