/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kavos113_karin_KarinJni */

#ifndef _Included_com_github_kavos113_karin_KarinJni
#define _Included_com_github_kavos113_karin_KarinJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kavos113_karin_KarinJni
 * Method:    applicationCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_KarinJni_applicationCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kavos113_karin_KarinJni
 * Method:    applicationCreateWindow
 * Signature: (JLjava/lang/String;IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_KarinJni_applicationCreateWindow
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jint);

/*
 * Class:     com_github_kavos113_karin_KarinJni
 * Method:    applicationRun
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_KarinJni_applicationRun
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
