#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <shaders_dir> <include_guard>"
  exit 1
fi

shaders_dir="$1"
include_guard="$2"

cd "$shaders_dir" || exit 1

output_file="shaders.h"
echo "// This file is auto-generated by scripts/shader.sh" > "$output_file"
echo "#ifndef $include_guard" >> "$output_file"
echo "#define $include_guard" >> "$output_file"

for shader_file in *.frag *.vert; do
  if [ -f "$shader_file" ]; then
    glslc "$shader_file" -o "${shader_file}.spv"
    xxd -i "${shader_file}.spv" >> "$output_file"
    echo "Compiled $shader_file"
  fi
done

sed -i 's/unsigned char/inline const unsigned char/' "$output_file"
sed -i 's/unsigned int/inline const unsigned int/' "$output_file"

echo "#endif // $include_guard" >> "$output_file"