#ifndef SRC_GRAPHICS_TEXT_FONT_LOADER_PLATFORM_H
#define SRC_GRAPHICS_TEXT_FONT_LOADER_PLATFORM_H

namespace karin
{
class IPlatformFontLoader
{
};
} // karin

#endif //SRC_GRAPHICS_TEXT_FONT_LOADER_PLATFORM_H