#ifndef SRC_GRAPHICS_TEXT_VULKAN_VULKAN_FONT_RENDERER_H
#define SRC_GRAPHICS_TEXT_VULKAN_VULKAN_FONT_RENDERER_H

namespace karin
{
class VulkanFontRenderer
{
};
} // karin

#endif //SRC_GRAPHICS_TEXT_VULKAN_VULKAN_FONT_RENDERER_H