#include "win_converter.h"

namespace karin
{
KeyEvent::KeyCode winVirtualKeyToKeyCode(WPARAM wParam)
{
    switch (wParam)
    {
    case VK_BACK:
        return KeyEvent::KeyCode::BACKSPACE;
    case VK_TAB:
        return KeyEvent::KeyCode::TAB;
    case VK_RETURN:
        return KeyEvent::KeyCode::ENTER;
    case VK_SHIFT:
        return KeyEvent::KeyCode::SHIFT;
    case VK_CONTROL:
        return KeyEvent::KeyCode::CONTROL;
    case VK_MENU:
        return KeyEvent::KeyCode::ALT;
    case VK_PAUSE:
        return KeyEvent::KeyCode::PAUSE;
    case VK_CAPITAL:
        return KeyEvent::KeyCode::CAPS_LOCK;
    case VK_KANA:
        return KeyEvent::KeyCode::KANA;
    case VK_KANJI:
        return KeyEvent::KeyCode::KANJI;
    case VK_ESCAPE:
        return KeyEvent::KeyCode::ESCAPE;
    case VK_CONVERT:
        return KeyEvent::KeyCode::CONVERT;
    case VK_NONCONVERT:
        return KeyEvent::KeyCode::NON_CONVERT;
    case VK_SPACE:
        return KeyEvent::KeyCode::SPACE;
    case VK_PRIOR:
        return KeyEvent::KeyCode::PAGE_UP;
    case VK_NEXT:
        return KeyEvent::KeyCode::PAGE_DOWN;
    case VK_END:
        return KeyEvent::KeyCode::END;
    case VK_HOME:
        return KeyEvent::KeyCode::HOME;
    case VK_LEFT:
        return KeyEvent::KeyCode::LEFT_ARROW;
    case VK_UP:
        return KeyEvent::KeyCode::UP_ARROW;
    case VK_RIGHT:
        return KeyEvent::KeyCode::RIGHT_ARROW;
    case VK_DOWN:
        return KeyEvent::KeyCode::DOWN_ARROW;
    case VK_SELECT:
        return KeyEvent::KeyCode::UNKNOWN;
    case VK_PRINT:
        return KeyEvent::KeyCode::UNKNOWN;
    case VK_EXECUTE:
        return KeyEvent::KeyCode::UNKNOWN;
    case VK_SNAPSHOT:
        return KeyEvent::KeyCode::PRINT_SCREEN;
    case VK_INSERT:
        return KeyEvent::KeyCode::INSERT;
    case VK_DELETE:
        return KeyEvent::KeyCode::DELETE_KEY;
    case VK_LWIN:
    case VK_RWIN:
        return KeyEvent::KeyCode::WINDOWS;
    case '0':
        return KeyEvent::KeyCode::NUM_0;
    case '1':
        return KeyEvent::KeyCode::NUM_1;
    case '2':
        return KeyEvent::KeyCode::NUM_2;
    case '3':
        return KeyEvent::KeyCode::NUM_3;
    case '4':
        return KeyEvent::KeyCode::NUM_4;
    case '5':
        return KeyEvent::KeyCode::NUM_5;
    case '6':
        return KeyEvent::KeyCode::NUM_6;
    case '7':
        return KeyEvent::KeyCode::NUM_7;
    case '8':
        return KeyEvent::KeyCode::NUM_8;
    case '9':
        return KeyEvent::KeyCode::NUM_9;
    case 'A':
        return KeyEvent::KeyCode::A;
    case 'B':
        return KeyEvent::KeyCode::B;
    case 'C':
        return KeyEvent::KeyCode::C;
    case 'D':
        return KeyEvent::KeyCode::D;
    case 'E':
        return KeyEvent::KeyCode::E;
    case 'F':
        return KeyEvent::KeyCode::F;
    case 'G':
        return KeyEvent::KeyCode::G;
    case 'H':
        return KeyEvent::KeyCode::H;
    case 'I':
        return KeyEvent::KeyCode::I;
    case 'J':
        return KeyEvent::KeyCode::J;
    case 'K':
        return KeyEvent::KeyCode::K;
    case 'L':
        return KeyEvent::KeyCode::L;
    case 'M':
        return KeyEvent::KeyCode::M;
    case 'N':
        return KeyEvent::KeyCode::N;
    case 'O':
        return KeyEvent::KeyCode::O;
    case 'P':
        return KeyEvent::KeyCode::P;
    case 'Q':
        return KeyEvent::KeyCode::Q;
    case 'R':
        return KeyEvent::KeyCode::R;
    case 'S':
        return KeyEvent::KeyCode::S;
    case 'T':
        return KeyEvent::KeyCode::T;
    case 'U':
        return KeyEvent::KeyCode::U;
    case 'V':
        return KeyEvent::KeyCode::V;
    case 'W':
        return KeyEvent::KeyCode::W;
    case 'X':
        return KeyEvent::KeyCode::X;
    case 'Y':
        return KeyEvent::KeyCode::Y;
    case 'Z':
        return KeyEvent::KeyCode::Z;
    case VK_SLEEP:
        return KeyEvent::KeyCode::UNKNOWN;
    case VK_NUMPAD0:
        return KeyEvent::KeyCode::NUMPAD_0;
    case VK_NUMPAD1:
        return KeyEvent::KeyCode::NUMPAD_1;
    case VK_NUMPAD2:
        return KeyEvent::KeyCode::NUMPAD_2;
    case VK_NUMPAD3:
        return KeyEvent::KeyCode::NUMPAD_3;
    case VK_NUMPAD4:
        return KeyEvent::KeyCode::NUMPAD_4;
    case VK_NUMPAD5:
        return KeyEvent::KeyCode::NUMPAD_5;
    case VK_NUMPAD6:
        return KeyEvent::KeyCode::NUMPAD_6;
    case VK_NUMPAD7:
        return KeyEvent::KeyCode::NUMPAD_7;
    case VK_NUMPAD8:
        return KeyEvent::KeyCode::NUMPAD_8;
    case VK_NUMPAD9:
        return KeyEvent::KeyCode::NUMPAD_9;
    case VK_MULTIPLY:
        return KeyEvent::KeyCode::NUMPAD_MULTIPLY;
    case VK_ADD:
        return KeyEvent::KeyCode::NUMPAD_ADD;
    case VK_SUBTRACT:
        return KeyEvent::KeyCode::NUMPAD_SUBTRACT;
    case VK_DECIMAL:
        return KeyEvent::KeyCode::NUMPAD_DECIMAL;
    case VK_DIVIDE:
        return KeyEvent::KeyCode::NUMPAD_DIVIDE;
    case VK_F1:
        return KeyEvent::KeyCode::F1;
    case VK_F2:
        return KeyEvent::KeyCode::F2;
    case VK_F3:
        return KeyEvent::KeyCode::F3;
    case VK_F4:
        return KeyEvent::KeyCode::F4;
    case VK_F5:
        return KeyEvent::KeyCode::F5;
    case VK_F6:
        return KeyEvent::KeyCode::F6;
    case VK_F7:
        return KeyEvent::KeyCode::F7;
    case VK_F8:
        return KeyEvent::KeyCode::F8;
    case VK_F9:
        return KeyEvent::KeyCode::F9;
    case VK_F10:
        return KeyEvent::KeyCode::F10;
    case VK_F11:
        return KeyEvent::KeyCode::F11;
    case VK_F12:
        return KeyEvent::KeyCode::F12;
    case VK_NUMLOCK:
        return KeyEvent::KeyCode::NUM_LOCK;
    case VK_SCROLL:
        return KeyEvent::KeyCode::SCROLL_LOCK;
    }
}
}
